version: "3.8"
services:
  app:
    build: .
    image: app:currency-exchange
    ports:
      - "3000:3000"
    volumes:
      - ".:/currency-exchange"
    container_name: currency_exchange_container
    command: npm start
